#!/bin/bash

logo="/usr/local/src/catfetch/logo"

# CPU
cpu=$(cat /proc/cpuinfo | grep "model name" | uniq | cut -c 14-)
cpu_freq=$(lscpu | grep "CPU max MHz" | cut -c 34-40)
cpu_cores=$(lscpu | grep Core | cut -d":" -f2 | sed -e 's/^[[:space:]]*//')

#GPU
gpu=$(lspci | grep VGA | cut -d"]" -f 2 | cut -d"[" -f2)

# OTHERS
memory=$(free -h | grep 'Mem' | awk '{ print ($3 " / " $2) }')
os=$(cat /etc/os-release | grep PRETTY_NAME | cut -d'"' -f2)
packages=$(pacman -Q | awk '{print $1}' | wc -l)
shell=$(echo $SHELL)
terminal=$(echo $TERM)
uptime=$(uptime -p | cut -c 4-)
user=$(echo $USER)
hostname=$(echo $HOSTNAME)

cat $logo

echo "┌──┤ $user@$hostname"
echo "│"
echo "├ CPU  : $cpu@$cpu_freq x $cpu_cores"
echo "├ GPU  : $gpu"
echo "├ Mem  : $memory"
echo "├ Shell: $shell"
echo "├ Term : $terminal"
echo "├ Pkgs : $packages"
echo "├ Uptm : $uptime"
echo "│"
echo "└───┤ $os"

